# render.yaml — Render Blueprint
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: churn-predictor-group1
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
    healthCheckPath: /_stcore/health
    autoDeploy: true        # auto-redeploy on every push to main branch
